[project]
name = 'Blockchain-Based-Communication-Message-Routing-Systems'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.delivery-tracking]
path = 'contracts/delivery-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.message-router-verification]
path = 'contracts/message-router-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
